services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306" # 호스트 포트 3307을 컨테이너 포트 3306으로 매핑
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-network

networks:
  spring-network:
