spring:
  application:
    name: baseback

  datasource:
    url: jdbc:mysql://mysql:3306/mydb
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: phFAgD1fUzpjf7d0gr9G
            client-secret: I1pdz9ybaS
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "http://34.132.79.107:8080/auth/naver/callback"
            scope:
              - name
              - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
