spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 실행 시마다 스키마를 생성 및 제거
    show-sql: true  # SQL 쿼리를 콘솔에 출력

# 외부 서비스 설정 무시 또는 대체
# security:
#   oauth2:
#     client:
#       registration:
#         naver:
#           client-id: TEST_CLIENT_ID
#           client-secret: TEST_CLIENT_SECRET
#       provider:
#         naver:
#           user-info-uri: https://dummy.api.com/v1/nid/me
